"""Added user_id to plots

Revision ID: 10a4a774c81f
Revises: 
Create Date: 2025-10-15 13:52:41.692767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '10a4a774c81f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('plots_ibfk_1'), 'plots', type_='foreignkey')
    op.create_foreign_key(None, 'plots', 'users', ['user_id'], ['id'])
    op.drop_column('plots', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plots', type_='foreignkey')
    op.create_foreign_key(op.f('plots_ibfk_1'), 'plots', 'users', ['owner_id'], ['id'])
    op.drop_column('plots', 'user_id')
    # ### end Alembic commands ###
